mqtt:
  host: mqtt-broker
  port: 1883
  topic_prefix: mqtt-io

# Streams
stream_modules:
  - name: qr-scanner
    module: usb
    vid: 0x0525
    pid: 0xA4AC
    read_size: 1024
    write_size: 64
    interface: 1
    read_interval: 1

  - name: tag-reader
    module: usb_hid
    vid: 0x03EB
    pid: 0x2421
    read_size: 64
    read_interval: 1

logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
  formatters:
    default:
      format: "%(asctime)s %(name)s [%(levelname)s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  loggers:
    mqtt_io:
      level: DEBUG
      handlers: [console]
      propagate: True
