services:
  mqtt-io:
    container_name: mqtt-io
    image: docker.chuxubank.top/chuxubank/mqtt-io:develop
    profiles:
      - mqtt-io
    depends_on:
      - mqtt-broker
    privileged: true
    user: root
    restart: unless-stopped
    volumes:
      - ./mqtt-io/config.yml:/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  hardware-proxy:
    container_name: hardware-proxy
    image: docker.chuxubank.top/chuxubank/hardware-proxy
    platform: linux/arm64
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  2mqtt:
    container_name: 2mqtt
    image: docker.chuxubank.top/mycontroller/2mqtt:1.5-devel
    profiles:
      - 2mqtt
    depends_on:
      - mqtt-broker
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./2mqtt/config.yaml:/app/config.yaml

  mqtt-broker:
    container_name: mqtt-broker
    image: docker.chuxubank.top/library/eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  mosquitto-data:
  mosquitto-log:
