services:
  mqtt-io:
    container_name: mqtt-io
    image: flyte/mqtt-io
    profiles:
      - mqtt-io
    privileged: true
    user: root
    restart: unless-stopped
    volumes:
      - ./mqtt-io/config.yml:/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  2mqtt:
    container_name: 2mqtt
    image: mycontroller/2mqtt:1.5-devel
    profiles:
      - 2mqtt
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./2mqtt/config.yaml:/app/config.yaml

  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  mosquitto-data:
  mosquitto-log:
