services:
  mqtt-io:
    container_name: mqtt-io
    image: docker.chuxubank.top/chuxubank/mqtt-io:restart
    profiles:
      - mqtt-io
    depends_on:
      - mqtt-broker
    privileged: true
    user: root
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./mqtt-io/config.yml
        target: /config.yml
        read_only: true
        bind:
          create_host_path: false
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  hardware-proxy:
    container_name: hardware-proxy
    image: docker.chuxubank.top/chuxubank/hardware-proxy
    platform: linux/arm64
    privileged: true
    user: root
    environment:
      QR_VID: "0x0525"
      QR_PID: "0xA4AC"
      QR_INTERFACE: "1"
      HF_VID: "0xFFFE"
      HF_PID: "0x0091"
      HF_INTERFACE: "0"
      UHF_VID: "0x03EB"
      UHF_PID: "0x2421"
      UHF_INTERFACE: "0"
    restart: unless-stopped
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  2mqtt:
    container_name: 2mqtt
    image: docker.chuxubank.top/mycontroller/2mqtt:1.5-devel
    profiles:
      - 2mqtt
    depends_on:
      - mqtt-broker
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./2mqtt/config.yaml:/app/config.yaml

  mqtt-broker:
    container_name: mqtt-broker
    image: docker.chuxubank.top/library/eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  mosquitto-data:
  mosquitto-log:
